name: Publish package to pypi on tag

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  build_wheel:
    name: Build wheel and publish to pypi
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Build Wheel
      run: |
        python setup.py sdist
        python setup.py bdist_wheel --universal
    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: false
