name: Publish package to pypi on tag

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
  
jobs:
  build_wheel:
    name: Build wheel and publish to pypi
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Build Wheel
      run: |
        python setup.py sdist
        python setup.py bdist_wheel --universal
    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: false
